# MoveIt uses this configuration for controller management

trajectory_execution:
  allowed_execution_duration_scaling: 5.0
  allowed_goal_duration_margin: 1.5
  allowed_start_tolerance: 0.01
  trajectory_duration_monitoring: false

moveit_controller_manager: moveit_simple_controller_manager/MoveItSimpleControllerManager

moveit_simple_controller_manager:
  controller_names:
    - arm
    - gripper

  arm:
    type: FollowJointTrajectory
    joints:
      - base_joint
      - shoulder_joint
      - elbow_joint
      - wrist_pitch_joint
      - wrist_roll_joint
    action_ns: follow_joint_trajectory
    default: true
  gripper:
    type: GripperCommand
    joints:
      - gripper_joint
    action_ns: gripper_cmd
    default: true
